tap "aquasecurity/trivy"
tap "azure/functions"
tap "azure/kubelogin"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/services"
brew "openssl@3"
brew "ansible"
brew "azcopy"
brew "azure-cli"
brew "colima", restart_service: true
brew "coreutils"
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "docker-credential-helper"
brew "flux"
brew "git"
brew "glab"
brew "helm"
brew "jq"
brew "k6"
brew "k8sgpt"
brew "kubernetes-cli"
brew "node"
brew "mongosh"
brew "nmap"
brew "nvm"
brew "openssh"
brew "openvpn"
brew "plantuml"
brew "pnpm"
brew "pyenv"
brew "sqlcmd"
brew "tree"
brew "vim"
brew "wget"
brew "yarn"
brew "zsh"
brew "aquasecurity/trivy/trivy"
brew "azure/functions/azure-functions-core-tools@4"
brew "azure/kubelogin/kubelogin"
brew "hashicorp/tap/terraform"
cask "1password", args: { appdir: "/Applications" }
cask "azure-data-studio", args: { appdir: "/Applications" }
cask "caffeine", args: { appdir: "/Applications" }
cask "dotnet-sdk", args: { appdir: "/Applications" }
cask "firefox", args: { appdir: "/Applications" }
cask "font-hack", args: { appdir: "/Applications" }
cask "font-roboto", args: { appdir: "/Applications" }
cask "google-chrome", args: { appdir: "/Applications" }
cask "iterm2", args: { appdir: "/Applications" }
cask "keka"
cask "microsoft-auto-update"
cask "microsoft-azure-storage-explorer", args: { appdir: "/Applications" }
cask "microsoft-remote-desktop", args: { appdir: "/Applications" }
cask "microsoft-teams", args: { appdir: "/Applications" }
cask "onedrive", args: { appdir: "/Applications" }
cask "openvpn-connect", args: { appdir: "/Applications" }
cask "postman", args: { appdir: "/Applications" }
cask "slack", args: { appdir: "/Applications" }
cask "spotify", args: { appdir: "/Applications" }
cask "visual-studio-code"
cask "whatsapp", args: { appdir: "/Applications" }
cask "yubico-yubikey-manager", args: { appdir: "/Applications" }
cask "zoom", args: { appdir: "/Applications" }
vscode "bencoleman.armview"
vscode "davidanson.vscode-markdownlint"
vscode "dotjoshjohnson.xml"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "golang.go"
vscode "hashicorp.terraform"
vscode "heaths.vscode-guid"
vscode "humao.rest-client"
vscode "k6.k6"
vscode "ms-azure-devops.azure-pipelines"
vscode "ms-azuretools.azure-dev"
vscode "ms-azuretools.vscode-apimanagement"
vscode "ms-azuretools.vscode-azureappservice"
vscode "ms-azuretools.vscode-azurecontainerapps"
vscode "ms-azuretools.vscode-azurefunctions"
vscode "ms-azuretools.vscode-azureresourcegroups"
vscode "ms-azuretools.vscode-azurestaticwebapps"
vscode "ms-azuretools.vscode-azurestorage"
vscode "ms-azuretools.vscode-azureterraform"
vscode "ms-azuretools.vscode-azurevirtualmachines"
vscode "ms-azuretools.vscode-bicep"
vscode "ms-azuretools.vscode-cosmosdb"
vscode "ms-azuretools.vscode-docker"
vscode "ms-azuretools.vscode-logicapps"
vscode "ms-dotnettools.csdevkit"
vscode "ms-dotnettools.csharp"
vscode "ms-dotnettools.vscode-dotnet-runtime"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-mssql.data-workspace-vscode"
vscode "ms-mssql.mssql"
vscode "ms-mssql.sql-bindings-vscode"
vscode "ms-mssql.sql-database-projects-vscode"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode.azure-account"
vscode "ms-vscode.azurecli"
vscode "ms-vscode.live-server"
vscode "ms-vscode.powershell"
vscode "ms-vscode.vscode-node-azure-pack"
vscode "ms-vscode.vscode-typescript-next"
vscode "ms-vsliveshare.vsliveshare"
vscode "msazurermtools.azurerm-vscode-tools"
vscode "prisma.prisma"
vscode "redhat.vscode-commons"
vscode "redhat.vscode-xml"
vscode "redhat.vscode-yaml"
vscode "ryu1kn.partial-diff"
vscode "vsciot-vscode.azure-iot-toolkit"
vscode "wasp-lang.wasp"
