tap "anomalyco/tap"
tap "aquasecurity/trivy"
tap "azure/functions"
tap "azure/kubelogin"
tap "grafana/grafana"
tap "grafana/tap"
tap "hashicorp/tap"
tap "oven-sh/bun"
brew "act"
brew "openssl@3"
brew "tree"
brew "ansible"
brew "azcopy"
brew "azure-cli"
brew "beads"
brew "certbot"
brew "checkov"
brew "colima", restart_service: :changed
brew "conftest"
brew "coreutils"
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "docker-credential-helper"
brew "ffmpeg"
brew "flux"
brew "fswatch"
brew "gh"
brew "gifsicle"
brew "git"
brew "glab"
brew "gnu-sed"
brew "go"
brew "helm"
brew "hf"
brew "jq"
brew "k6"
brew "k8sgpt"
brew "ko"
brew "kubernetes-cli"
brew "libpq"
brew "llama.cpp"
brew "node"
brew "mongosh"
brew "nmap"
brew "nvm"
brew "ollama", restart_service: :changed
brew "openssh"
brew "openvpn"
brew "pi-coding-agent"
brew "pkgconf"
brew "plantuml"
brew "pnpm"
brew "postgresql@16"
brew "pyenv"
brew "semgrep"
brew "snyk-agent-scan"
brew "sqlcmd"
brew "tmux"
brew "typescript"
brew "uv"
brew "vim"
brew "wget"
brew "yarn"
brew "zsh"
brew "anomalyco/tap/opencode"
brew "aquasecurity/trivy/trivy"
brew "azure/kubelogin/kubelogin"
brew "grafana/grafana/gcx"
brew "hashicorp/tap/terraform"
brew "oven-sh/bun/bun"
cask "1password", args: { appdir: "/Applications" }
cask "1password-cli"
cask "balenaetcher"
cask "caffeine", args: { appdir: "/Applications" }
cask "claude-code"
cask "cloudflare-warp"
cask "copilot-cli"
cask "dotnet-sdk", args: { appdir: "/Applications" }
cask "firefox", args: { appdir: "/Applications" }
cask "font-hack", args: { appdir: "/Applications" }
cask "font-roboto", args: { appdir: "/Applications" }
cask "gcloud-cli"
cask "ghostty"
cask "google-chrome", args: { appdir: "/Applications" }
cask "iterm2", args: { appdir: "/Applications" }
cask "keka"
cask "microsoft-auto-update"
cask "microsoft-azure-storage-explorer", args: { appdir: "/Applications" }
cask "microsoft-teams", args: { appdir: "/Applications" }
cask "obsidian"
cask "onedrive", args: { appdir: "/Applications" }
cask "openvpn-connect", args: { appdir: "/Applications" }
cask "postman", args: { appdir: "/Applications" }
cask "slack", args: { appdir: "/Applications" }
cask "spotify", args: { appdir: "/Applications" }
cask "visual-studio-code"
cask "whatsapp", args: { appdir: "/Applications" }
cask "windows-app"
cask "yubico-authenticator"
cask "zoom", args: { appdir: "/Applications" }
vscode "bierner.markdown-mermaid"
vscode "davidanson.vscode-markdownlint"
vscode "docker.docker"
vscode "dotjoshjohnson.xml"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "github.vscode-github-actions"
vscode "golang.go"
vscode "hashicorp.terraform"
vscode "humao.rest-client"
vscode "jasonnutter.vscode-codeowners"
vscode "ms-azure-load-testing.microsoft-testing"
vscode "ms-azuretools.azure-dev"
vscode "ms-azuretools.vscode-azure-github-copilot"
vscode "ms-azuretools.vscode-azure-mcp-server"
vscode "ms-azuretools.vscode-azureappservice"
vscode "ms-azuretools.vscode-azurecontainerapps"
vscode "ms-azuretools.vscode-azurefunctions"
vscode "ms-azuretools.vscode-azureresourcegroups"
vscode "ms-azuretools.vscode-azurestaticwebapps"
vscode "ms-azuretools.vscode-azurestorage"
vscode "ms-azuretools.vscode-azureterraform"
vscode "ms-azuretools.vscode-azurevirtualmachines"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-cosmosdb"
vscode "ms-azuretools.vscode-docker"
vscode "ms-dotnettools.vscode-dotnet-runtime"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-mssql.data-workspace-vscode"
vscode "ms-mssql.mssql"
vscode "ms-mssql.sql-bindings-vscode"
vscode "ms-mssql.sql-database-projects-vscode"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-vscode.azurecli"
vscode "ms-vscode.live-server"
vscode "ms-vscode.powershell"
vscode "ms-vscode.vscode-node-azure-pack"
vscode "ms-vscode.vscode-typescript-next"
vscode "ms-vsliveshare.vsliveshare"
vscode "ms-windows-ai-studio.windows-ai-studio"
vscode "prisma.prisma"
vscode "redhat.vscode-xml"
vscode "redhat.vscode-yaml"
vscode "ryu1kn.partial-diff"
vscode "teamsdevapp.vscode-ai-foundry"
vscode "tsandall.opa"
go "golang.org/x/tools/gopls"
go "honnef.co/go/tools/cmd/staticcheck"
npm "@googleworkspace/cli"
npm "@mermaid-js/mermaid-cli"
npm "@ollama/pi-web-search"
npm "corepack"
npm "node-gyp"
npm "prisma"
npm "tsx"
